CREATE DATABASE IF NOT EXISTS ticketLon CHARACTER SET utf8 COLLATE utf8_czech_ci;
GRANT ALL PRIVILEGES ON ticketLon.* TO pc@localhost IDENTIFIED BY 'pc';

USE ticketLon;

CREATE TABLE IF NOT EXISTS News (
  idNews INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  added DATETIME NOT NULL,
  text VARCHAR(9999) NOT NULL,
  INDEX(name)
) engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Type (
  idType INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500),
  INDEX(name)
) engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Place (
  idPlace INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  street VARCHAR(200) NOT NULL,
  city VARCHAR(80) NOT NULL,
  zipCode VARCHAR(10) NOT NULL,
  numberOfPlaces INT(4) NOT NULL,
  INDEX(name)
) engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Event (
  idEvent INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  date DATETIME NOT NULL,
  duration INT(4) NOT NULL,
  description VARCHAR(9999),
  numberOfFreeTickets INT(4) NOT NULL,
  priceOfOneTicket DOUBLE NOT NULL,
  Type_idType INT(4) UNSIGNED NOT NULL,
  Place_idPlace INT(4) UNSIGNED NOT NULL,
  FOREIGN KEY (Type_idType) REFERENCES Type(idType),
  FOREIGN KEY (Place_idPlace) REFERENCES Place(idPlace),
  INDEX(title)
) engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS User (
  idUser INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(200) NOT NULL,
  password VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  surname VARCHAR(100) NOT NULL,
  INDEX(username)
) engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Role (
  idRole INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  roleName VARCHAR(100) NOT NULL,
  description VARCHAR(500) NOT NULL,
  INDEX(roleName)
) engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Role_has_User (
  Role_idRole INT(4) UNSIGNED NOT NULL,
  User_idUser INT(4) UNSIGNED NOT NULL,
  FOREIGN KEY (Role_idRole) REFERENCES Role(idRole),
  FOREIGN KEY (User_idUser) REFERENCES User(idUser)
) engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Reservation (
  idReservation INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  User_idUser INT(4) UNSIGNED NOT NULL,
  Event_idEvent INT(4) UNSIGNED NOT NULL,
  numberOfTickets INT(4) NOT NULL,
  added DATETIME NOT NULL,
  FOREIGN KEY (User_idUser) REFERENCES User(idUser),
  FOREIGN KEY (Event_idEvent) REFERENCES Event(idEvent)
) engine=InnoDB DEFAULT CHARSET=utf8;
